# Site settings
title: Luis Accorsi
email: luis@accorsi.cc
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://accorsi.cc" # the base hostname & protocol for your site
twitter_username: luis.accorsi
github_username:  accorsi

# Build settings
markdown: kramdown

port:  4000
host:  0.0.0.0